### ISSUE TITLE
CDKTF Support ( Error: unknown type {"nesting_mode":"set"}) 

### ISSUE THREAD

**Issue by lukesmith-flutter** [cisco-open/terraform-provider-meraki#113]
**Is your feature request related to a problem? Please describe.**
Unable to add provider using CDKTF

**Describe the solution you'd like**
When using "cdktf provider add" its unable to install the provider

**Describe alternatives you've considered**
Using terraform not CDKTF
attempted to use previous versions of the provider but still not working

**Additional context**
`cdktf provider add cisco-open/meraki@0.2.7-alpha
[2024-07-18T10:48:26.475] [INFO] default - Checking whether pre-built provider exists for the following constraints:
  provider: cisco-open/meraki
  version : 0.2.7-alpha
  language: typescript
  cdktf   : 0.19.2

[2024-07-18T10:48:26.779] [INFO] default - Pre-built provider does not exist for the given constraints.
[2024-07-18T10:48:26.780] [INFO] default - Adding local provider registry.terraform.io/cisco-open/meraki with version constraint 0.2.7-alpha to cdktf.json
Local providers have been updated. Running cdktf get to update...
Error: unknown type {"nesting_mode":"set"}
    at LQ.renderAttributeType (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:110:32177)
    at LQ.addAnonymousStruct (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:110:34785)
    at LQ.renderAttributeType (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:110:31951)
    at LQ.renderAttributesForBlock (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:110:32480)
    at LQ.resourceFrom (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:110:29762)
    at dC.parse (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:110:35583)
    at /usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:115:12948
    at Array.map (<anonymous>)
    at fC.buildResourceModels (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:115:12915)
    at fC.emitProvider (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:115:13376)
⠦ downloading and generating modules and providers...
Error: unknown type {"nesting_mode":"set"}`

**Comment by lukesmith-flutter** [comment]
Worked on cdktf 20.6
