### ISSUE TITLE
`meraki_networks_switch_link_aggregations` - crash

### ISSUE THREAD

**Issue by mcparaf** [cisco-open/terraform-provider-meraki#150]
When performing unrelated operations, meraki_networks_switch_link_aggregations randomly crashed.

```
Stack trace from the terraform-provider-meraki_v0.2.11-alpha plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1010eef84]

goroutine 249 [running]:
github.com/cisco-open/terraform-provider-meraki/internal/provider.(*NetworksSwitchLinkAggregationsResource).Read(0x1400038c008, {0x101c24ee8, 0x14000826b70}, {{{{0x101c2cce8, 0x1400002a2d0}, {0x1019a4940, 0x1400098ff50}}, {0x101c3ee88, 0x14000887db0}}, 0x1400038c190, ...}, ...)
	github.com/cisco-open/terraform-provider-meraki/internal/provider/resource_meraki_networks_switch_link_aggregations.go:276 +0x574
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x140001e21e0, {0x101c24ee8, 0x14000826b70}, 0x14000826c00, 0x1400091f6a8)
	github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_readresource.go:117 +0x698
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x140001e21e0, {0x101c24ee8?, 0x14000826a50?}, 0x14000239340)
	github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_readresource.go:55 +0x314
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x140001eca00, {0x101c24ee8?, 0x14000826210?}, 0x140001fc000)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:784 +0x224
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x101bd51e0?, 0x140001eca00}, {0x101c24ee8, 0x14000826210}, 0x140001a6880, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001a3000, {0x101c24ee8, 0x14000826180}, {0x101c3d370, 0x140003ec000}, 0x1400082a000, 0x14000307a10, 0x1024983c8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xba0
google.golang.org/grpc.(*Server).handleStream(0x140001a3000, {0x101c3d370, 0x140003ec000}, 0x1400082a000)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xc80
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x150

Error: The terraform-provider-meraki_v0.2.11-alpha plugin crashed!
```

**Comment by fmunozmiranda** [comment]
Please try it with new version and update us.
