### ISSUE TITLE
resource `meraki_networks_appliance_vlans` "vlan_1" ipv6 error

### ISSUE THREAD

**Issue by finkjordanj** [cisco-open/terraform-provider-meraki#51]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When setting the ipv6 configuration block enable to false getting error.

```
resource "meraki_networks_appliance_vlans" "this_vlan_1" {
  network_id                = local.this_network.id
  name                      = "MGMT"
  id                        = "1" 
  appliance_ip              = "10.76.237.17"
  subnet                    = "10.76.237.16/28"
  dhcp_handling             = "Run a DHCP server"
  dhcp_lease_time           = "1 day"
  dns_nameservers           = "upstream_dns"
  dhcp_boot_options_enabled = false
  ipv6 = {
    enabled = false
  }
  mandatory_dhcp = {
    enabled = false
  }
}
```

**Expected behavior**
When applying when the enable set to false all other options not be needed for ipv6 options. If options are left off and configuration changed in the dashboard the terraform doesn't track and try to revert the configuration.

Error on Apply

**Screenshots**

```
fink@LTWXCGVT333:~/dev/meraki-terraform-test $ terraform apply
Acquiring state lock. This may take a few moments...
data.meraki_networks.dev_networks: Reading...
meraki_devices.this_mx: Refreshing state... [name=750-comm-meraki-lab-mx1]
data.meraki_networks.dev_networks: Read complete after 1s
meraki_networks_appliance_settings.this: Refreshing state...
meraki_networks_appliance_firewall_firewalled_services.this_snmp: Refreshing state...
meraki_networks_syslog_servers.this_spoke: Refreshing state...
meraki_networks_appliance_vlans_settings.this_vlans: Refreshing state...
meraki_networks_appliance_firewall_firewalled_services.this_icmp: Refreshing state...
meraki_networks_appliance_firewall_firewalled_services.this_web: Refreshing state...
meraki_networks_group_policies.group_policy_byod: Refreshing state... [name=BYOD]
meraki_networks_group_policies.group_policy_guest: Refreshing state... [name=GUEST]
meraki_networks_group_policies.group_policy_pan: Refreshing state... [name=PAN]
meraki_networks_group_policies.group_policy_internal: Refreshing state... [name=INTERNAL]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # meraki_devices.this_mx will be updated in-place
  ~ resource "meraki_devices" "this_mx" {
      ~ details           = [] -> (known after apply)
      ~ firmware          = "wired-18-1-07" -> (known after apply)
      + floor_plan_id     = (known after apply)
      ~ imei              = null -> (known after apply)
      ~ lan_ip            = null -> (known after apply)
      ~ mac               = "2c:3f:0b:b4:9b:61" -> (known after apply)
      ~ model             = "MX67" -> (known after apply)
      + move_map_marker   = true
        name              = "750-comm-meraki-lab-mx1"
      ~ network_id        = "L_783626335162467749" -> (known after apply)
      ~ product_type      = null -> (known after apply)
      + switch_profile_id = (known after apply)
      + tags              = (known after apply)
        # (5 unchanged attributes hidden)
    }

  # meraki_networks_appliance_vlans.this_vlan_1 will be created
  + resource "meraki_networks_appliance_vlans" "this_vlan_1" {
      + appliance_ip              = "10.76.237.17"
      + dhcp_boot_filename        = (known after apply)
      + dhcp_boot_next_server     = (known after apply)
      + dhcp_boot_options_enabled = false
      + dhcp_handling             = "Run a DHCP server"
      + dhcp_lease_time           = "1 day"
      + dhcp_options              = (known after apply)
      + dhcp_relay_server_ips     = (known after apply)
      + dns_nameservers           = "upstream_dns"
      + group_policy_id           = (known after apply)
      + id                        = "1"
      + interface_id              = (known after apply)
      + ipv6                      = {
          + enabled            = false
          + prefix_assignments = (known after apply)
        }
      + mandatory_dhcp            = {
          + enabled = false
        }
      + mask                      = (known after apply)
      + name                      = "MGMT"
      + network_id                = "L_783626335162467749"
      + reserved_ip_ranges        = (known after apply)
      + subnet                    = "10.76.237.16/28"
      + template_vlan_type        = (known after apply)
      + vpn_nat_subnet            = (known after apply)
    }

Plan: 1 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

meraki_networks_appliance_vlans.this_vlan_1: Creating...
meraki_devices.this_mx: Modifying... [name=750-comm-meraki-lab-mx1]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-meraki_v0.2.1-alpha plugin:

panic: reflect: call of reflect.Value.Type on zero Value

goroutine 15 [running]:
reflect.Value.typeSlow({0x0?, 0x0?, 0xc00013da30?})
        reflect/value.go:2634 +0x113
reflect.Value.Type(...)
        reflect/value.go:2629
terraform-provider-meraki/internal/provider.changeStructUnknowns({0x1267ec0, 0x0?}, {0x1267e80?, 0xc0003112c0?})
        terraform-provider-meraki/internal/provider/utils.go:761 +0x245
terraform-provider-meraki/internal/provider.changeStructUnknowns({0x13eee60, 0xc00041f800?}, {0x13eee60?, 0xc00041f810?})
        terraform-provider-meraki/internal/provider/utils.go:807 +0xbe5
terraform-provider-meraki/internal/provider.mergeInterfaces({0x1587fc0, 0xc00001e1e0}, {0x1587fc0, 0xc00001e3c0}, 0x1)
        terraform-provider-meraki/internal/provider/utils.go:694 +0x14b2
terraform-provider-meraki/internal/provider.ResponseApplianceGetNetworkApplianceVLANItemToBodyRs({{0x2, {0xc00051c4f8, 0x14}}, {0x2, {0xc0005022d0, 0xc}}, {0x0, {0x0, 0x0}}, {0x1, ...}, ...}, ...)
        terraform-provider-meraki/internal/provider/resource_meraki_networks_appliance_vlans.go:1160 +0x9ee
terraform-provider-meraki/internal/provider.(*NetworksApplianceVLANsResource).Create(0xc00053a028, {0x189d928, 0xc0004c8ba0}, {{{{0x18a55b0, 0xc000691440}, {0x133d360, 0xc000690630}}, {0x18b7880, 0xc0005080f0}}, {{{0x18a55b0, ...}, ...}, ...}, ...}, ...)
        terraform-provider-meraki/internal/provider/resource_meraki_networks_appliance_vlans.go:459 +0x4bc
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000201040, {0x189d928, 0xc0004c8ba0}, 0xc00013f580, 0xc00013f520)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0005576d8?, {0x189d928, 0xc0004c8ba0}, 0xc000458320, 0xc00013f6d8)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000201040, {0x189d928?, 0xc0004c8a80?}, 0xc000458280)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/proto6server/server_applyresourcechange.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000232820, {0x189d928?, 0xc000690240?}, 0xc0005381c0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/tf6server/server.go:846 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1564480?, 0xc000232820}, {0x189d928, 0xc000690240}, 0xc0001be800, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001bb000, {0x189d928, 0xc000565680}, {0x18b5cf8, 0xc0003f8000}, 0xc0000206c0, 0xc00031b620, 0x20eca38, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001bb000, {0x18b5cf8, 0xc0003f8000}, 0xc0000206c0)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-meraki_v0.2.1-alpha plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version:1.8.3
* Meraki provider version:0.2.1-alpha
* OS Version:  ubuntu 22.04

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @finkjordanj could you please try it again with v0.2.2-apha and update if it works now?

**Comment by finkjordanj** [comment]
Confirmed resolved with ipv6 config option block enabled and setting ipv6 enabled to false and applied correctly.
