### ISSUE TITLE
meraki_networks_wireless_rf_profiles plugin crash

### ISSUE THREAD

**Issue by efernando87** [cisco-open/terraform-provider-meraki#90]
**Prerequisites**
* [V] Have you tested the operation in the API directly?
* [V] Do you have the latest Terraform provider version?
* [V] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Error: The terraform-provider-meraki_v0.2.5-alpha plugin crashed! 
when running meraki_networks_wireless_rf_profiles resource 

**Expected behavior**
should run smoothly according to terraform plan

**Screenshots**
module.meraki.meraki_networks_wireless_rf_profiles.basic_rf_profiles[0]: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-meraki_v0.2.5-alpha plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x19d6811]

goroutine 65 [running]:
github.com/go-resty/resty/v2.(*Response).StatusCode(...)
        github.com/go-resty/resty/v2@v2.13.1/response.go:66
github.com/cisco-open/terraform-provider-meraki/internal/provider.(*NetworksWirelessRfProfilesResource).Create(0xc000080040, {0x24d1268, 0xc00015d200}, {{{{0x24d8f70, 0xc0003af440}, {0x1f5ea40, 0xc00038c7e0}}, {0x24eb240, 0xc00009e050}}, {{{0x24d8f70, ...}, ...}, ...}, ...}, ...)
        github.com/cisco-open/terraform-provider-meraki/internal/provider/resource_meraki_networks_wireless_rf_profiles.go:1507 +0x3b1
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc00018bd40, {0x24d1268, 0xc00015d200}, 0xc000297580, 0xc000297520)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0006136d8?, {0x24d1268, 0xc00015d200}, 0xc00014e820, 0xc0002976d8)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc00018bd40, {0x24d1268?, 0xc00015d080?}, 0xc00014e6e0)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/proto6server/server_applyresourcechange.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0002ae820, {0x24d1268?, 0xc00015c600?}, 0xc0000ce000)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x218a760?, 0xc0002ae820}, {0x24d1268, 0xc00015c600}, 0xc000136000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022b000, {0x24d1268, 0xc00015c570}, {0x24e96b8, 0xc000002180}, 0xc00021a000, 0xc00038b8f0, 0x2d6e318, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc00022b000, {0x24e96b8, 0xc000002180}, 0xc00021a000)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 8
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-meraki_v0.2.5-alpha plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: v1.8.3
* Meraki provider version: v0.2.5-alpha
* OS Version: 

**Additional context**

my code is look like this.

resource "meraki_networks_wireless_rf_profiles" "basic_rf_profiles" {
  network_id               = meraki_networks.network.network_id
  band_selection_type      = "ap"
  client_balancing_enabled = false
  name                     = "Test Indoor Profile"
  five_ghz_settings = {
    channel_width = "20"
    max_power     = 30
    min_bitrate   = 24
    min_power     = 8
  }
  two_four_ghz_settings = {
    ax_enabled  = true
    max_power   = 30
    min_bitrate = 11.0
    min_power   = 5
  }
  ap_band_settings = {
    band_operation_mode   = "dual"
    band_steering_enabled = true
    bands = {
      enabled = ["2.4", "5"]
    }
  }
}

**Comment by efernando87** [comment]
cancel this request as issue already raised here:
https://github.com/cisco-open/terraform-provider-meraki/issues/88
